name: "DoViRemux"
guid: "2f215b63-1a73-4193-9102-78f84d027014"
version: 3.3.0
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "katiekloss"
overview: "Automatically remux Dolby Vision files"
description: >
  Remuxes media with Dolby Vision profile metadata from MKV to MP4, for better support on LG WebOS TVs.

category: "General"
artifacts:
  - "Jellyfin.Plugin.DoViRemux.dll"
changelog: |-
  - Plugin now supports Jellyfin 10.11
